services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    # volumes:
    depends_on:
      - neo4jdb
      - postgresdb
    restart: always
    networks:
      - postgres_net
      - neo4j_net
    volumes:
      - ./app:/app

  neo4jdb:
    image: neo4j:4.4.0-enterprise
    restart: always
    ports:
      # - "7473:7473" # HTTPS
      - "7474:7474" # HTTP
      - "7687:7687" # BOLT
    # volumes:
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc"]
    networks:
      - neo4j_net
    volumes:
      - neo4jdb:/data

  postgresdb:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_SERVER: postgresserver
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks:
      - postgres_net
    volumes:
      - postgresdb:/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgresdb
    environment:
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:5050"
    networks:
      - postgres_net
    volumes:
      - pgadmin:/data

volumes:
  neo4jdb:
  postgresdb:
  pgadmin:

networks:
  neo4j_net:
  postgres_net:

# This is to be used with okteto. On docker-compose, comment the lines bellow.
# endpoints:
#   web:
#     - path: /
#       service: app
#       port: 8080
#     # - path: /neo4jbrowser
#     #   service: neo4jdb
#     #   port: 7474
#     - path: /pgadmin
#       service: pgadmin
#       port: 5050
